import "./input/dag/calculate-depths-snapshot";
console.log(1, "/",8, "./input/dag/calculate-depths-snapshot");
import "./input/dag/calculate-direct-parents-snapshot";
console.log(2, "/",8, "./input/dag/calculate-direct-parents-snapshot");
import "./input/finite-automaton/dfa/dfa-collection";
console.log(3, "/",8, "./input/finite-automaton/dfa/dfa-collection");
import "./input/finite-automaton/dfa/util/intersection/test-00";
console.log(4, "/",8, "./input/finite-automaton/dfa/util/intersection/test-00");
import "./input/finite-automaton/dfa/util/union/test-00";
console.log(5, "/",8, "./input/finite-automaton/dfa/util/union/test-00");
import "./input/finite-automaton/nfa/nfa-collection";
console.log(6, "/",8, "./input/finite-automaton/nfa/nfa-collection");
import "./input/finite-automaton/nfa/util/intersection/test-00";
console.log(7, "/",8, "./input/finite-automaton/nfa/util/intersection/test-00");
import "./input/finite-automaton/nfa/util/union/test-00";
console.log(8, "/",8, "./input/finite-automaton/nfa/util/union/test-00");