import "./input/dag/calculate-depths-snapshot";
console.log(1, "/",11, "./input/dag/calculate-depths-snapshot");
import "./input/dag/calculate-direct-parents-snapshot";
console.log(2, "/",11, "./input/dag/calculate-direct-parents-snapshot");
import "./input/finite-automaton/dfa/dfa-collection";
console.log(3, "/",11, "./input/finite-automaton/dfa/dfa-collection");
import "./input/finite-automaton/dfa/util/from-nfa/test-00";
console.log(4, "/",11, "./input/finite-automaton/dfa/util/from-nfa/test-00");
import "./input/finite-automaton/dfa/util/intersection/test-00";
console.log(5, "/",11, "./input/finite-automaton/dfa/util/intersection/test-00");
import "./input/finite-automaton/dfa/util/union/test-00";
console.log(6, "/",11, "./input/finite-automaton/dfa/util/union/test-00");
import "./input/finite-automaton/nfa/nfa-collection";
console.log(7, "/",11, "./input/finite-automaton/nfa/nfa-collection");
import "./input/finite-automaton/nfa/util/concatenation/test-00";
console.log(8, "/",11, "./input/finite-automaton/nfa/util/concatenation/test-00");
import "./input/finite-automaton/nfa/util/intersection/test-00";
console.log(9, "/",11, "./input/finite-automaton/nfa/util/intersection/test-00");
import "./input/finite-automaton/nfa/util/union/test-00";
console.log(10, "/",11, "./input/finite-automaton/nfa/util/union/test-00");
import "./input/finite-automaton/regular-expression/util/from-string/test-00";
console.log(11, "/",11, "./input/finite-automaton/regular-expression/util/from-string/test-00");